### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by elbasel** [buunguyen/topbar#16]
When using with nextjs in the _app.js file
and reloading the page the above error is given.
but if we use HMR after initial page load the error doesn't happen.

is the module trying to access window before initialization by next js?
`
import NavBar from "../components/NavBar";
import { useLoading } from "../lib/hooks";
import topbar from "topbar";
import "../styles/globals.css";

topbar.config({
  barColors: {
    0: "rgba(26,  188, 156, .7)",
    ".3": "rgba(41,  128, 185, .7)",
    "1.0": "rgba(231, 76,  60,  .7)",
  },
});

function MyApp({ Component, pageProps }) {
  const loading = useLoading();
  loading ? topbar.show() : topbar.hide();
  return (
    <>
      {loading && <div>Loading</div>}
      <NavBar />
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
`

**Comment by trkoch** [comment]
May have been fixed with https://github.com/buunguyen/topbar/pull/17. Can you check?

**Comment by arielvieira** [comment]
@trkoch this is still happening after #17.

For anyone else that is having this issue here is the answer.

This is happening in Next.js because the `topbar` is a client side library that use the `window` object, and next.js tries to render it in the server first and that causes the next.js to throw the `window is not defined` error

I would recommend you creating a component for handling this topbar loading logic and using [Next.js Dynamic Import](https://nextjs.org/docs/advanced-features/dynamic-import) with `ssr: false` to make sure the topbar is only running in the client side.

```js
import dynamic from 'next/dynamic'
const Component = dynamic(() => import('./Component'), { ssr: false })
```

this will work for `pages` dir, not sure if will work for `app` dir

**Comment by buunguyen** [comment]
I suppose the solution by @arielvieira works. Closing this now.
